name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Code style check and binary-compatibility check
        # Run locally with: sbt 'verifyCodeStyle ; mimaReportBinaryIssues'
        run: sbt "; verifyCodeStyle; mimaReportBinaryIssues"

      - name: Compile all code with fatal warnings for Scala 2.12 and 2.13
        # Run locally with: env CI=true sbt 'clean ; Test/compile ; It/compile'
        run: sbt "; +Test/compile;"

      - name: Create all API docs for artifacts/website and all reference docs
        # Run locally with: sbt verifyDocs
        run: sbt docs/paradox

  test-java8-scala212:
    name: Build and Test (Java 8, Scala 2.12)
    runs-on: ubuntu-18.04
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Scala with JDK 8
        uses: olafurpg/setup-scala@v10

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Run tests with Scala 2.12 and AdoptOpenJDK 8
        run: sbt "++2.12.13 test"

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;        

  test-java8-scala213:
    name: Build and Test (Java 8, Scala 2.13)
    runs-on: ubuntu-18.04
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Scala with JDK 8
        uses: olafurpg/setup-scala@v10

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Run tests with Scala 2.13 and AdoptOpenJDK 8
        run: sbt "++2.13.4 test"

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;

  test-java11-scala212:
    name: Build and Test (Java 11, Scala 2.12)
    runs-on: ubuntu-18.04
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Scala with JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Run tests with Scala 2.12 and AdoptOpenJDK 11
        run: sbt "++2.12.13 test" -J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;

  test-java11-scala213:
    name: Build and Test (Java 11, Scala 2.13)
    runs-on: ubuntu-18.04
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Scala with JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Run tests with Scala 2.13 and AdoptOpenJDK 11
        run: sbt "++2.13.4 test" -J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;   

  it-test-mysql-java11-scala213:
    name: MySQL integration tests with Scala 2.13 and AdoptOpenJDK 11
    runs-on: ubuntu-18.04
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
          
      - name: Setup Scala with JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Start docker
        run: ./scripts/launch-mysql.sh

      - name: Run tests with Scala 2.13 and AdoptOpenJDK 11
        run: sbt "++2.13.4 It/testOnly akka.persistence.jdbc.integration.MySQL*" -J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;                

  it-test-postgres-java11-scala213:
    name: Postgres integration tests with Scala 2.13 and AdoptOpenJDK 11
    runs-on: ubuntu-18.04
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
          
      - name: Setup Scala with JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Start docker
        run: ./scripts/launch-postgres.sh

      - name: Run tests with Scala 2.13 and AdoptOpenJDK 11
        run: sbt "++2.13.4 It/testOnly akka.persistence.jdbc.integration.Postgres*" -J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;                        

  it-test-oracle-java11-scala213:
    name: Oracle integration tests with Scala 2.13 and AdoptOpenJDK 11
    runs-on: ubuntu-18.04
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
          
      - name: Setup Scala with JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Start docker
        run: ./scripts/launch-oracle.sh

      - name: Run tests with Scala 2.13 and AdoptOpenJDK 11
        run: sbt "++2.13.4 It/testOnly akka.persistence.jdbc.integration.Oracle*" -J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;   

  it-test-sqlserver-java11-scala213:
    name: SQL Server integration tests with Scala 2.13 and AdoptOpenJDK 11
    runs-on: ubuntu-18.04
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
          
      - name: Setup Scala with JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Start docker
        run: ./scripts/launch-sqlserver.sh

      - name: Run tests with Scala 2.13 and AdoptOpenJDK 11
        run: sbt "++2.13.4 It/testOnly akka.persistence.jdbc.integration.SqlServer*" -J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;                   