name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Code style check and binary-compatibility check
        # Run locally with: sbt 'verifyCodeStyle ; mimaReportBinaryIssues'
        run: sbt "; verifyCodeStyle; mimaReportBinaryIssues"

      - name: Compile all code with fatal warnings for Scala 2.12 and 2.13
        # Run locally with: env CI=true sbt 'clean ; Test/compile ; It/compile'
        run: sbt "; +Test/compile;"

      - name: Create all API docs for artifacts/website and all reference docs
        # Run locally with: sbt verifyDocs
        run: sbt docs/paradox