name: test-java8-scala213

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-java8-scala213:
    name: Build and Test with AdoptOpenJDK 8 and Scala 2.13
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Scala with JDK
        uses: olafurpg/setup-scala@v10

      - name: Cache Coursier cache
        uses: coursier/cache-action@v5

      - name: Run tests
        run: sbt "++2.13.4 test"

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;        
